### ISSUE TITLE
通过锚点获取实例有问题

### ISSUE THREAD

**Issue by cdoky** [uxyheaven/XYRouter#7]
@{@"title": @"TestVC1#viewControllerWithStr1:str2:,你好,世界!"}
通过锚点获取到的UIViewController实例会自动dealloc~~

解决方案:
    [invocation invoke];
    void _returnValue;
    [invocation getReturnValue:&returnValue];
    return (__bridge UIViewController_)returnValue;

**Comment by uxyheaven** [comment]
thanks
